
plot_dir: /home/xzcappon/phd/tools/puma/examples/yuma_plots/dset
plot_timestamp: True
samples:
  ttbar:
    sample: ttbar
    latex: $t\overline{t}$
    cuts: ["pt > 20000", "pt < 250000", "eta < 2.5", "eta > -2.5"]
  zprime:
    sample: zprime
    latex: Z'
    cuts: ["pt > 250000", "pt < 5000000",  "eta < 2.5", "eta > -2.5"]


datasets_config: datasets.yaml
datasets:
  - mc20
  - mc23

denominator: mc20

variables:
  jets:
    - pt_btagJes
    - eta_btagJes
    - HadronConeExclTruthLabelPt
    - HadronConeExclTruthLabelLxy
    - pt
    - eta
    - mass
    - n_tracks
  tracks:
    - d0
    - z0SinTheta
    - dphi
    - deta
    - qOverP
    - IP3D_signed_d0_significance
    - IP3D_signed_z0_significance
    - phiUncertainty
    - thetaUncertainty
    - qOverPUncertainty
    - numberOfPixelHits
    - numberOfSCTHits
    - numberOfInnermostPixelLayerHits
    - numberOfNextToInnermostPixelLayerHits
    - numberOfInnermostPixelLayerSharedHits
    - numberOfInnermostPixelLayerSplitHits
    - numberOfPixelSharedHits
    - numberOfPixelSplitHits
    - numberOfSCTSharedHits
    - leptonID
    - ftagTruthOriginLabel

plots:

    # plot all histograms
    - type: histogram
      var: all

    